const std = @import("std");

// QuickJS version string, read from the VERSION file at build time.
const version_raw = @embedFile("VERSION");

// C sources that make up libquickjs. As modules are ported to Zig they are
// removed from this list and pulled in via `zig/root.zig` instead.
const lib_c_sources = [_][]const u8{
    "quickjs.c",
    "dtoa.c",
    "libregexp.c",
    "libunicode.c",
    "cutils.c",
    "quickjs-libc.c",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{ .preferred_optimize_mode = .ReleaseFast });

    const version = std.mem.trim(u8, version_raw, " \t\r\n");

    // Flags shared by every C translation unit.
    const c_flags = [_][]const u8{
        "-fwrapv", // signed overflow is well-defined, like the Makefile build
        "-D_GNU_SOURCE",
        b.fmt("-DCONFIG_VERSION=\"{s}\"", .{version}),
        "-DHAVE_CLOSEFROM", // glibc >= 2.34 / BSD provide closefrom()
        "-Wno-implicit-fallthrough",
    };

    // ----- libquickjs (static) -----------------------------------------
    // The library's root is a Zig file that pulls in the ported modules; the
    // remaining C sources are compiled into the same artifact and link against
    // the exported C-ABI symbols.
    const lib_mod = b.createModule(.{
        .root_source_file = b.path("zig_root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    lib_mod.addCSourceFiles(.{
        .files = &lib_c_sources,
        .flags = &c_flags,
    });

    const lib = b.addLibrary(.{
        .name = "quickjs",
        .root_module = lib_mod,
        .linkage = .static,
    });
    b.installArtifact(lib);

    // Helper to wire a C frontend executable against libquickjs.
    const Ctx = struct {
        b: *std.Build,
        target: std.Build.ResolvedTarget,
        optimize: std.builtin.OptimizeMode,
        lib: *std.Build.Step.Compile,
        flags: []const []const u8,

        fn exeModule(ctx: @This()) *std.Build.Module {
            const m = ctx.b.createModule(.{
                .target = ctx.target,
                .optimize = ctx.optimize,
                .link_libc = true,
            });
            m.linkLibrary(ctx.lib);
            m.linkSystemLibrary("m", .{});
            m.linkSystemLibrary("pthread", .{});
            m.linkSystemLibrary("dl", .{});
            return m;
        }
    };
    const ctx = Ctx{
        .b = b,
        .target = target,
        .optimize = optimize,
        .lib = lib,
        .flags = &c_flags,
    };

    // ----- qjsc (bytecode compiler, built first) -----------------------
    const qjsc_mod = ctx.exeModule();
    qjsc_mod.addCSourceFiles(.{
        .files = &.{"qjsc.c"},
        .flags = &c_flags,
    });
    qjsc_mod.addCMacro("CONFIG_CC", "\"zig cc\"");
    qjsc_mod.addCMacro("CONFIG_PREFIX", "\"/usr/local\"");
    const qjsc = b.addExecutable(.{ .name = "qjsc", .root_module = qjsc_mod });
    b.installArtifact(qjsc);

    // ----- repl.c is generated by qjsc ---------------------------------
    const repl_run = b.addRunArtifact(qjsc);
    repl_run.addArgs(&.{ "-s", "-c", "-o" });
    const repl_c = repl_run.addOutputFileArg("repl.c");
    repl_run.addArg("-m");
    repl_run.addFileArg(b.path("repl.js"));

    // ----- qjs (interpreter / REPL) ------------------------------------
    const qjs_mod = ctx.exeModule();
    qjs_mod.addCSourceFiles(.{
        .files = &.{"qjs.c"},
        .flags = &c_flags,
    });
    qjs_mod.addCSourceFile(.{ .file = repl_c, .flags = &c_flags });
    const qjs = b.addExecutable(.{ .name = "qjs", .root_module = qjs_mod });
    b.installArtifact(qjs);

    // ----- run-test262 -------------------------------------------------
    const t262_mod = ctx.exeModule();
    t262_mod.addCSourceFiles(.{
        .files = &.{"run-test262.c"},
        .flags = &c_flags,
    });
    const run_test262 = b.addExecutable(.{ .name = "run-test262", .root_module = t262_mod });
    b.installArtifact(run_test262);

    // ----- `zig build run` runs qjs ------------------------------------
    const run_step = b.step("run", "Run the qjs interpreter");
    const run_cmd = b.addRunArtifact(qjs);
    run_step.dependOn(&run_cmd.step);

    // ----- `zig build test` runs the JS test suite ---------------------
    const test_step = b.step("test", "Run the QuickJS JS test suite");
    const TestSpec = struct { args: []const []const u8 };
    const tests = [_]TestSpec{
        .{ .args = &.{"tests/test_closure.js"} },
        .{ .args = &.{"tests/test_language.js"} },
        .{ .args = &.{ "--std", "tests/test_builtin.js" } },
        .{ .args = &.{"tests/test_loop.js"} },
        .{ .args = &.{"tests/test_bigint.js"} },
        .{ .args = &.{"tests/test_cyclic_import.js"} },
        .{ .args = &.{"tests/test_worker.js"} },
        .{ .args = &.{"tests/test_std.js"} },
        .{ .args = &.{"tests/test_rw_handler.js"} },
    };
    for (tests) |t| {
        const tr = b.addRunArtifact(qjs);
        tr.setCwd(b.path("."));
        tr.addArgs(t.args);
        test_step.dependOn(&tr.step);
    }
}
