/*
 * Regular Expression Engine
 *
 * Copyright (c) 2017-2018 Fabrice Bellard
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <assert.h>

#include "cutils.h"
#include "libregexp.h"
#include "libunicode.h"

/*
  TODO:
  - remove REOP_char_i and REOP_range_i by precomputing the case folding.
  - add specific opcodes for simple unicode property tests so that the
    generated bytecode is smaller.
  - Add a lock step execution mode (=linear time execution guaranteed)
    when the regular expression is "simple" i.e. no backreference nor
    complicated lookahead. The opcodes are designed for this execution
    model.
*/

#if defined(TEST) 
#define DUMP_REOP
#endif
//#define DUMP_REOP
//#define DUMP_EXEC

typedef enum {
#define DEF(id, size) REOP_ ## id,
#include "libregexp-opcode.h"
#undef DEF
    REOP_COUNT,
} REOPCodeEnum;

#define CAPTURE_COUNT_MAX 255
#define REGISTER_COUNT_MAX 255
/* must be large enough to have a negligible runtime cost and small
   enough to call the interrupt callback often. */
#define INTERRUPT_COUNTER_INIT 10000

/* unicode code points */
#define CP_LS   0x2028
#define CP_PS   0x2029

#define TMP_BUF_SIZE 128

typedef struct {
    DynBuf byte_code;
    const uint8_t *buf_ptr;
    const uint8_t *buf_end;
    const uint8_t *buf_start;
    int re_flags;
    BOOL is_unicode;
    BOOL unicode_sets; /* if set, is_unicode is also set */
    BOOL ignore_case;
    BOOL multi_line;
    BOOL dotall;
    uint8_t group_name_scope;
    int capture_count;
    int total_capture_count; /* -1 = not computed yet */
    int has_named_captures; /* -1 = don't know, 0 = no, 1 = yes */
    void *opaque;
    DynBuf group_names;
    union {
        char error_msg[TMP_BUF_SIZE];
        char tmp_buf[TMP_BUF_SIZE];
    } u;
} REParseState;

typedef struct {
#ifdef DUMP_REOP
    const char *name;
#endif
    uint8_t size;
} REOpCode;

static const REOpCode reopcode_info[REOP_COUNT] = {
#ifdef DUMP_REOP
#define DEF(id, size) { #id, size },
#else
#define DEF(id, size) { size },
#endif
#include "libregexp-opcode.h"
#undef DEF
};

#define RE_HEADER_FLAGS          0
#define RE_HEADER_CAPTURE_COUNT  2
#define RE_HEADER_REGISTER_COUNT 3
#define RE_HEADER_BYTECODE_LEN   4

#define RE_HEADER_LEN 8

static inline int is_digit(int c) {
    return c >= '0' && c <= '9';
}

/* ported to Zig (libregexp.zig) */

typedef struct REString {
    struct REString *next;
    uint32_t hash;
    uint32_t len;
    uint32_t buf[];
} REString;

typedef struct {
    /* the string list is the union of 'char_range' and of the strings
       in hash_table[]. The strings in hash_table[] have a length !=
       1. */
    CharRange cr;
    uint32_t n_strings;
    uint32_t hash_size;
    int hash_bits;
    REString **hash_table;
} REStringList;

/* The following are ported to Zig (libregexp.zig). */
int dbuf_insert(DynBuf *s, int pos, int len);
uint32_t re_string_hash(int len, const uint32_t *buf);
int re_emit_range(REParseState *s, const CharRange *cr);
int re_string_cmp_len(const void *a, const void *b, void *arg);
void re_emit_char(REParseState *s, int c);
void re_string_list_init(REParseState *s1, REStringList *s);
void re_string_list_free(REStringList *s);
int re_string_find2(REStringList *s, int len, const uint32_t *buf, uint32_t h0, BOOL add_flag);
int re_string_find(REStringList *s, int len, const uint32_t *buf, BOOL add_flag);
int re_string_add(REStringList *s, int len, const uint32_t *buf);
int re_string_list_op(REStringList *a, REStringList *b, int op);
int re_string_list_canonicalize(REParseState *s1, REStringList *s, BOOL is_unicode);
int cr_init_char_range(REParseState *s, REStringList *cr, uint32_t c);
int re_emit_string_list(REParseState *s, const REStringList *sl);

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

static void lre_print_char(int c, BOOL is_range)
{
    if (c == '\'' || c == '\\' ||
        (is_range && (c == '-' || c == ']'))) {
        printf("\\%c", c);
    } else if (c >= ' ' && c <= 126) {
        printf("%c", c);
    } else {
        printf("\\u{%04x}", c);
    }
}

static __maybe_unused void re_string_list_dump(const char *str, const REStringList *s)
{
    REString *p;
    const CharRange *cr;
    int i, j, k;

    printf("%s:\n", str);
    printf("  ranges: [");
    cr = &s->cr;
    for(i = 0; i < cr->len; i += 2) {
        lre_print_char(cr->points[i], TRUE);
        if (cr->points[i] != cr->points[i + 1] - 1) {
            printf("-");
            lre_print_char(cr->points[i + 1] - 1, TRUE);
        }
    }
    printf("]\n");
    
    j = 0;
    for(i = 0; i < s->hash_size; i++) {
        for(p = s->hash_table[i]; p != NULL; p = p->next) {
            printf("  %d/%d: '", j, s->n_strings);
            for(k = 0; k < p->len; k++) {
                lre_print_char(p->buf[k], FALSE);
            }
            printf("'\n");
            j++;
        }
    }
}

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

static const uint16_t char_range_d[] = {
    1,
    0x0030, 0x0039 + 1,
};

/* code point ranges for Zs,Zl or Zp property */
static const uint16_t char_range_s[] = {
    10,
    0x0009, 0x000D + 1,
    0x0020, 0x0020 + 1,
    0x00A0, 0x00A0 + 1,
    0x1680, 0x1680 + 1,
    0x2000, 0x200A + 1,
    /* 2028;LINE SEPARATOR;Zl;0;WS;;;;;N;;;;; */
    /* 2029;PARAGRAPH SEPARATOR;Zp;0;B;;;;;N;;;;; */
    0x2028, 0x2029 + 1,
    0x202F, 0x202F + 1,
    0x205F, 0x205F + 1,
    0x3000, 0x3000 + 1,
    /* FEFF;ZERO WIDTH NO-BREAK SPACE;Cf;0;BN;;;;;N;BYTE ORDER MARK;;;; */
    0xFEFF, 0xFEFF + 1,
};

static const uint16_t char_range_w[] = {
    4,
    0x0030, 0x0039 + 1,
    0x0041, 0x005A + 1,
    0x005F, 0x005F + 1,
    0x0061, 0x007A + 1,
};

#define CLASS_RANGE_BASE 0x40000000

typedef enum {
    CHAR_RANGE_d,
    CHAR_RANGE_D,
    CHAR_RANGE_s,
    CHAR_RANGE_S,
    CHAR_RANGE_w,
    CHAR_RANGE_W,
} CharRangeEnum;

static const uint16_t * const char_range_table[] = {
    char_range_d,
    char_range_s,
    char_range_w,
};

/* ported to Zig (libregexp.zig) */

#ifdef DUMP_REOP
static __maybe_unused void lre_dump_bytecode(const uint8_t *buf,
                                                     int buf_len)
{
    int pos, len, opcode, bc_len, re_flags, i;
    uint32_t val, val2;

    assert(buf_len >= RE_HEADER_LEN);

    re_flags = lre_get_flags(buf);
    bc_len = get_u32(buf + RE_HEADER_BYTECODE_LEN);
    assert(bc_len + RE_HEADER_LEN <= buf_len);
    printf("flags: 0x%x capture_count=%d reg_count=%d\n",
           re_flags, buf[RE_HEADER_CAPTURE_COUNT], buf[RE_HEADER_REGISTER_COUNT]);
    if (re_flags & LRE_FLAG_NAMED_GROUPS) {
        const char *p;
        p = (char *)buf + RE_HEADER_LEN + bc_len;
        printf("named groups: ");
        for(i = 1; i < buf[RE_HEADER_CAPTURE_COUNT]; i++) {
            if (i != 1)
                printf(",");
            printf("<%s>", p);
            p += strlen(p) + LRE_GROUP_NAME_TRAILER_LEN;
        }
        printf("\n");
        assert(p == (char *)(buf + buf_len));
    }
    printf("bytecode_len=%d\n", bc_len);

    buf += RE_HEADER_LEN;
    pos = 0;
    while (pos < bc_len) {
        printf("%5u: ", pos);
        opcode = buf[pos];
        len = reopcode_info[opcode].size;
        if (opcode >= REOP_COUNT) {
            printf(" invalid opcode=0x%02x\n", opcode);
            break;
        }
        if ((pos + len) > bc_len) {
            printf(" buffer overflow (opcode=0x%02x)\n", opcode);
            break;
        }
        printf("%s", reopcode_info[opcode].name);
        switch(opcode) {
        case REOP_char:
        case REOP_char_i:
            val = get_u16(buf + pos + 1);
            if (val >= ' ' && val <= 126)
                printf(" '%c'", val);
            else
                printf(" 0x%04x", val);
            break;
        case REOP_char32:
        case REOP_char32_i:
            val = get_u32(buf + pos + 1);
            if (val >= ' ' && val <= 126)
                printf(" '%c'", val);
            else
                printf(" 0x%08x", val);
            break;
        case REOP_goto:
        case REOP_split_goto_first:
        case REOP_split_next_first:
        case REOP_lookahead:
        case REOP_negative_lookahead:
            val = get_u32(buf + pos + 1);
            val += (pos + 5);
            printf(" %u", val);
            break;
        case REOP_loop:
            val2 = buf[pos + 1];
            val = get_u32(buf + pos + 2);
            val += (pos + 6);
            printf(" r%u, %u", val2, val);
            break;
        case REOP_loop_split_goto_first:
        case REOP_loop_split_next_first:
        case REOP_loop_check_adv_split_goto_first:
        case REOP_loop_check_adv_split_next_first:
            {
                uint32_t limit;
                val2 = buf[pos + 1];
                limit = get_u32(buf + pos + 2);
                val = get_u32(buf + pos + 6);
                val += (pos + 10);
                printf(" r%u, %u, %u", val2, limit, val);
            }
            break;
        case REOP_save_start:
        case REOP_save_end:
            printf(" %u", buf[pos + 1]);
            break;
        case REOP_back_reference:
        case REOP_back_reference_i:
        case REOP_backward_back_reference:
        case REOP_backward_back_reference_i:
            {
                int n, i;
                n = buf[pos + 1];
                len += n;
                for(i = 0; i < n; i++) {
                    if (i != 0)
                        printf(",");
                    printf(" %u", buf[pos + 2 + i]);
                }
            }
            break;
        case REOP_save_reset:
            printf(" %u %u", buf[pos + 1], buf[pos + 2]);
            break;
        case REOP_set_i32:
            val = buf[pos + 1];
            val2 = get_u32(buf + pos + 2);
            printf(" r%u, %d", val, val2);
            break;
        case REOP_set_char_pos:
        case REOP_check_advance:
            val = buf[pos + 1];
            printf(" r%u", val);
            break;
        case REOP_range:
        case REOP_range_i:
            {
                int n, i;
                n = get_u16(buf + pos + 1);
                len += n * 4;
                for(i = 0; i < n * 2; i++) {
                    val = get_u16(buf + pos + 3 + i * 2);
                    printf(" 0x%04x", val);
                }
            }
            break;
        case REOP_range32:
        case REOP_range32_i:
            {
                int n, i;
                n = get_u16(buf + pos + 1);
                len += n * 8;
                for(i = 0; i < n * 2; i++) {
                    val = get_u32(buf + pos + 3 + i * 4);
                    printf(" 0x%08x", val);
                }
            }
            break;
        default:
            break;
        }
        printf("\n");
        pos += len;
    }
}
#endif

/* The bytecode emit helpers are ported to Zig (libregexp.zig). */
void re_emit_op(REParseState *s, int op);
int re_emit_op_u32(REParseState *s, int op, uint32_t val);
int re_emit_goto(REParseState *s, int op, uint32_t val);
int re_emit_goto_u8(REParseState *s, int op, uint32_t arg, uint32_t val);
int re_emit_goto_u8_u32(REParseState *s, int op, uint32_t arg0, uint32_t arg1, uint32_t val);
void re_emit_op_u8(REParseState *s, int op, uint32_t val);
void re_emit_op_u16(REParseState *s, int op, uint32_t val);

/* The following parser helpers are ported to Zig (libregexp.zig). */
int parse_digits(const uint8_t **pp, BOOL allow_overflow);
int re_parse_expect(REParseState *s, const uint8_t **pp, int c);
BOOL is_unicode_char(int c);
int find_group_name(REParseState *s, const char *name, BOOL emit_group_index);
BOOL is_duplicate_group_name(REParseState *s, const char *name, int scope);
int re_parse_modifiers(REParseState *s, const uint8_t **pp);
BOOL update_modifier(BOOL val, int add_mask, int remove_mask, int mask);
int re_parse_group_name(char *buf, int buf_size, const uint8_t **pp);
int re_parse_captures(REParseState *s, int *phas_named_captures, const char *capture_name, BOOL emit_group_index);
int re_count_captures(REParseState *s);
BOOL re_has_named_captures(REParseState *s);

int __attribute__((format(printf, 2, 3))) re_parse_error(REParseState *s, const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(s->u.error_msg, sizeof(s->u.error_msg), fmt, ap);
    va_end(ap);
    return -1;
}

static int re_parse_out_of_memory(REParseState *s)
{
    return re_parse_error(s, "out of memory");
}

/* If allow_overflow is false, return -1 in case of
   overflow. Otherwise return INT32_MAX. */
/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* Parse an escape sequence, *pp points after the '\':
   allow_utf16 value:
   0 : no UTF-16 escapes allowed
   1 : UTF-16 escapes allowed
   2 : UTF-16 escapes allowed and escapes of surrogate pairs are
   converted to a unicode character (unicode regexp case).

   Return the unicode char and update *pp if recognized,
   return -1 if malformed escape,
   return -2 otherwise. */
/* lre_parse_escape is ported to Zig (libregexp.zig). */

#ifdef CONFIG_ALL_UNICODE
/* XXX: we use the same chars for name and value */
/* ported to Zig (libregexp.zig) */

/* XXX: memory error test */
/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */
#endif /* CONFIG_ALL_UNICODE */

int parse_unicode_property(REParseState *s, REStringList *cr, const uint8_t **pp, BOOL is_inv, BOOL allow_sequence_prop);
int parse_class_string_disjunction(REParseState *s, REStringList *cr, const uint8_t **pp);
int re_parse_char_class(REParseState *s, const uint8_t **pp);
BOOL re_need_check_adv_and_capture_init(BOOL *pneed_capture_init, const uint8_t *bc_buf, int bc_buf_len);
int get_class_atom(REParseState *s, REStringList *cr,
                          const uint8_t **pp, BOOL inclass);

/* ported to Zig (libregexp.zig) */

/* return -1 if error otherwise the character or a class range
   (CLASS_RANGE_BASE) if cr != NULL. In case of class range, 'cr' is
   initialized. Otherwise, it is ignored. */
/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */


/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* need_check_adv: false if the opcodes always advance the char pointer
   need_capture_init: true if all the captures in the atom are not set
*/
/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* if capture_name = NULL: return the number of captures + 1.
   Otherwise, return the number of matching capture groups  */
/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

int re_parse_disjunction(REParseState *s, BOOL is_backward_dir);

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* re_parse_term is ported to Zig (libregexp.zig). */

/* ported to Zig (libregexp.zig) */

/* ported to Zig (libregexp.zig) */

/* Allocate the registers as a stack. The control flow is recursive so
   the analysis can be linear. */
/* compute_register_count is ported to Zig (libregexp.zig). */
int compute_register_count(uint8_t *bc_buf, int bc_buf_len);

/* ported to Zig (libregexp.zig) */

/* 'buf' must be a zero terminated UTF-8 string of length buf_len.
   Return NULL if error and allocate an error message in *perror_msg,
   otherwise the compiled bytecode and its length in plen.
*/
/* ported to Zig (libregexp.zig) */

/* The regexp executor (is_line_terminator, the GET/PEEK/PREV_CHAR macros,
   REExecContext/StackElem, lre_poll_timeout, stack_realloc,
   lre_exec_backtrack and lre_exec) is ported to Zig (libregexp.zig). */

/* lre_get_alloc_count, lre_get_capture_count, lre_get_flags and
   lre_get_groupnames are ported to Zig (libregexp.zig). */

#ifdef TEST

BOOL lre_check_stack_overflow(void *opaque, size_t alloca_size)
{
    return FALSE;
}

void *lre_realloc(void *opaque, void *ptr, size_t size)
{
    return realloc(ptr, size);
}

int main(int argc, char **argv)
{
    int len, flags, ret, i;
    uint8_t *bc;
    char error_msg[64];
    uint8_t *capture;
    const char *input;
    int input_len, capture_count;

    if (argc < 4) {
        printf("usage: %s regexp flags input\n", argv[0]);
        return 1;
    }
    flags = atoi(argv[2]);
    bc = lre_compile(&len, error_msg, sizeof(error_msg), argv[1],
                     strlen(argv[1]), flags, NULL);
    if (!bc) {
        fprintf(stderr, "error: %s\n", error_msg);
        exit(1);
    }

    input = argv[3];
    input_len = strlen(input);

    capture = malloc(sizeof(capture[0]) * lre_get_alloc_count(bc));
    ret = lre_exec(capture, bc, (uint8_t *)input, 0, input_len, 0, NULL);
    printf("ret=%d\n", ret);
    if (ret == 1) {
        capture_count = lre_get_capture_count(bc);
        for(i = 0; i < 2 * capture_count; i++) {
            uint8_t *ptr;
            ptr = capture[i];
            printf("%d: ", i);
            if (!ptr)
                printf("<nil>");
            else
                printf("%u", (int)(ptr - (uint8_t *)input));
            printf("\n");
        }
    }
    free(capture);
    return 0;
}
#endif

/* Exports for the Zig port (libregexp.zig). REOpCode is a 1-byte struct
   { uint8_t size; }, so reopcode_info can be viewed as a flat size array. */
const uint8_t *const zig_reopcode_size = (const uint8_t *)reopcode_info;
const int zig_REGISTER_COUNT_MAX = REGISTER_COUNT_MAX;
const int zig_REOP_set_i32        = REOP_set_i32;
const int zig_REOP_set_char_pos   = REOP_set_char_pos;
const int zig_REOP_check_advance  = REOP_check_advance;
const int zig_REOP_loop           = REOP_loop;
const int zig_REOP_loop_split_goto_first = REOP_loop_split_goto_first;
const int zig_REOP_loop_split_next_first = REOP_loop_split_next_first;
const int zig_REOP_loop_check_adv_split_goto_first = REOP_loop_check_adv_split_goto_first;
const int zig_REOP_loop_check_adv_split_next_first = REOP_loop_check_adv_split_next_first;
const int zig_REOP_range          = REOP_range;
const int zig_REOP_range_i        = REOP_range_i;
const int zig_REOP_range32        = REOP_range32;
const int zig_REOP_range32_i      = REOP_range32_i;
const int zig_REOP_back_reference          = REOP_back_reference;
const int zig_REOP_back_reference_i        = REOP_back_reference_i;
const int zig_REOP_backward_back_reference   = REOP_backward_back_reference;
const int zig_REOP_backward_back_reference_i = REOP_backward_back_reference_i;

/* Remaining opcode constants for the Zig executor port (drift check + use). */
const int zig_REOP_invalid = REOP_invalid;
const int zig_REOP_char = REOP_char;
const int zig_REOP_char_i = REOP_char_i;
const int zig_REOP_char32 = REOP_char32;
const int zig_REOP_char32_i = REOP_char32_i;
const int zig_REOP_dot = REOP_dot;
const int zig_REOP_any = REOP_any;
const int zig_REOP_space = REOP_space;
const int zig_REOP_not_space = REOP_not_space;
const int zig_REOP_line_start = REOP_line_start;
const int zig_REOP_line_start_m = REOP_line_start_m;
const int zig_REOP_line_end = REOP_line_end;
const int zig_REOP_line_end_m = REOP_line_end_m;
const int zig_REOP_goto = REOP_goto;
const int zig_REOP_split_goto_first = REOP_split_goto_first;
const int zig_REOP_split_next_first = REOP_split_next_first;
const int zig_REOP_match = REOP_match;
const int zig_REOP_lookahead_match = REOP_lookahead_match;
const int zig_REOP_negative_lookahead_match = REOP_negative_lookahead_match;
const int zig_REOP_save_start = REOP_save_start;
const int zig_REOP_save_end = REOP_save_end;
const int zig_REOP_save_reset = REOP_save_reset;
const int zig_REOP_word_boundary = REOP_word_boundary;
const int zig_REOP_word_boundary_i = REOP_word_boundary_i;
const int zig_REOP_not_word_boundary = REOP_not_word_boundary;
const int zig_REOP_not_word_boundary_i = REOP_not_word_boundary_i;
const int zig_REOP_lookahead = REOP_lookahead;
const int zig_REOP_negative_lookahead = REOP_negative_lookahead;
const int zig_REOP_prev = REOP_prev;
